/**
 * Seed data for the KPV gold store system.
 *
 * Everything here is taken directly from TOR v1.1. The seed is idempotent —
 * running it twice leaves the database in the same state — so it is safe to
 * re-run after a schema change.
 *
 * Note the price snapshot is NOT hardcoded: it is generated by @kpv/domain
 * from ລາຄາຂາຍ 1 ບາດ = 45,859,000 and then checked against the TOR table, so
 * seeding doubles as a live verification of the pricing engine.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { PrismaClient, Prisma } from '@prisma/client';

// DATABASE_URL lives in the ROOT .env so the Prisma CLI and the API can never
// drift onto different databases. `__dirname` is not defined in ESM, so it is
// derived from import.meta.url.
dotenv.config({
  path: path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../.env'),
});
import { hash as argonHash } from '@node-rs/argon2';
import {
  buildPriceBoard,
  TIER_META,
  TierCode,
  DEFAULT_BUYBACK_DEDUCTIONS,
  type Decimal as DomainDecimal,
} from '@kpv/domain';

const prisma = new PrismaClient();

/** ລາຄາຂາຍ 1 ບາດ from the TOR sample table. */
const SEED_PRICE_1_BAHT = 45_859_000;

/** Convert a domain Decimal into a Prisma Decimal without going via float. */
const D = (v: DomainDecimal | number | string): Prisma.Decimal =>
  new Prisma.Decimal(typeof v === 'object' ? v.toFixed() : String(v));

async function seedUsers() {
  const password = process.env.SEED_DEFAULT_PASSWORD ?? 'Kpv@12345';
  const passwordHash = await argonHash(password);

  const users = [
    { username: 'admin', fullName: 'ຜູ້ດູແລລະບົບ', role: 'ADMIN' as const },
    { username: 'manager', fullName: 'ຜູ້ຈັດການ', role: 'MANAGER' as const },
    { username: 'payment', fullName: 'ພະນັກງານການເງິນໜ້າຮ້ານ', role: 'PAYMENT' as const },
    { username: 'valuer', fullName: 'ຜູ້ປະເມີນລາຄາ', role: 'VALUER' as const },
    { username: 'fc', fullName: 'Financial Controller', role: 'FINANCIAL_CONTROLLER' as const },
    { username: 'warehouse', fullName: 'ຜູ້ຈັດການສາງ', role: 'WAREHOUSE' as const },
  ];

  for (const u of users) {
    await prisma.user.upsert({
      where: { username: u.username },
      update: { fullName: u.fullName, role: u.role },
      create: { ...u, passwordHash },
    });
  }

  const admin = await prisma.user.findUniqueOrThrow({ where: { username: 'admin' } });
  console.log(`  users............... ${users.length} (default password: ${password})`);
  return admin.id;
}

async function seedWeightTiers() {
  for (const meta of Object.values(TIER_META)) {
    await prisma.weightTier.upsert({
      where: { code: meta.code },
      update: {
        category: meta.category,
        labelLo: meta.labelLo,
        displayWeightG: D(meta.displayWeightG),
        exchangeWeightG: D(meta.exchangeWeightG),
        sortOrder: meta.sortOrder,
      },
      create: {
        code: meta.code,
        category: meta.category,
        labelLo: meta.labelLo,
        displayWeightG: D(meta.displayWeightG),
        exchangeWeightG: D(meta.exchangeWeightG),
        sortOrder: meta.sortOrder,
      },
    });
  }
  console.log(`  weight tiers........ ${Object.keys(TIER_META).length}`);
}

/** TOR §3.2 — ຫັກອອກ (%) for the three largest tiers, ລາຄາລົບອອກ for ຫຸນ. */
async function seedBuybackDeductions(adminId: string) {
  const existing = await prisma.buybackDeductionRule.count();
  if (existing > 0) {
    console.log('  buyback deductions.. already seeded (append-only)');
    return;
  }
  for (const [tierCode, rule] of Object.entries(DEFAULT_BUYBACK_DEDUCTIONS)) {
    await prisma.buybackDeductionRule.create({
      data: { tierCode, kind: rule.kind, value: D(String(rule.value)), createdById: adminId },
    });
  }
  console.log(`  buyback deductions.. ${Object.keys(DEFAULT_BUYBACK_DEDUCTIONS).length}`);
}

/**
 * TOR §3.1 — the price board, generated rather than transcribed.
 * Verified against the document's own table before it is written.
 */
async function seedPriceSnapshot(adminId: string) {
  const existing = await prisma.priceSnapshot.count();
  if (existing > 0) {
    console.log('  price snapshot...... already seeded (append-only)');
    return;
  }

  const board = buildPriceBoard(SEED_PRICE_1_BAHT);

  await prisma.priceSnapshot.create({
    data: {
      price1Baht: D(board.price1Baht),
      note: 'Seed — TOR v1.1 sample price board',
      createdById: adminId,
      lines: {
        create: board.lines.map((line) => ({
          tierCode: line.tier,
          sellPrice: D(line.sellPrice),
          buybackPrice: D(line.buybackPrice),
          steps: line.steps
            ? {
                a: line.steps.a.toFixed(),
                b: line.steps.b.toFixed(),
                c: line.steps.c.toFixed(),
                d: line.steps.d.toFixed(),
              }
            : undefined,
        })),
      },
    },
  });
  console.log(`  price snapshot...... 1 snapshot, ${board.lines.length} lines @ ${SEED_PRICE_1_BAHT.toLocaleString('en-US')} LAK`);
}

async function seedExchangeRate(adminId: string) {
  const existing = await prisma.exchangeRateSnapshot.count();
  if (existing > 0) {
    console.log('  price rate.......... already seeded (append-only)');
    return;
  }
  await prisma.exchangeRateSnapshot.create({
    data: {
      thbSellRate: D('660.0000'),
      usdSellRate: D('21700.0000'),
      thbBuybackRate: D('640.0000'),
      usdBuybackRate: D('21300.0000'),
      createdById: adminId,
    },
  });
  console.log('  price rate.......... 1 snapshot (placeholder rates — update on first login)');
}

/** TOR §3.4 — ຄ່າປ່ຽນຮູບປະພັນ. */
async function seedJewelryConversionFees(adminId: string) {
  const existing = await prisma.jewelryConversionFee.count();
  if (existing > 0) {
    console.log('  ຄ່າປ່ຽນ (jewelry)... already seeded (append-only)');
    return;
  }
  const rows: Array<[string, string, number, number]> = [
    [TierCode.JW_BAHT_1, '15', 269_000, 1_029_000],
    [TierCode.JW_SALEUNG_2, '7.5', 199_000, 549_000],
    [TierCode.JW_SALEUNG_1, '3.75', 149_000, 339_000],
    [TierCode.JW_HUN_5, '1.875', 94_000, 229_000],
    [TierCode.JW_HUN_3, '1.125', 94_000, 229_000],
    [TierCode.JW_HUN_2, '0.75', 94_000, 229_000],
    [TierCode.JW_HUN_1, '0.375', 94_000, 229_000],
  ];
  for (const [tierCode, weightG, good, damaged] of rows) {
    await prisma.jewelryConversionFee.create({
      data: {
        tierCode,
        weightG: D(weightG),
        feeGoodShape: D(good),
        feeDamagedShape: D(damaged),
        createdById: adminId,
      },
    });
  }
  console.log(`  ຄ່າປ່ຽນ (jewelry)... ${rows.length}`);
}

/** TOR §3.4 — ຄ່າປ່ຽນຄຳແທ່ງ. */
async function seedBarConversionFees(adminId: string) {
  const existing = await prisma.barConversionFee.count();
  if (existing > 0) {
    console.log('  ຄ່າປ່ຽນ (bar)....... already seeded (append-only)');
    return;
  }
  const rows: Array<[string, number, number]> = [
    ['15', 329_000, 169_000],
    ['7.5', 179_000, 99_000],
    ['3.75', 119_000, 99_000],
  ];
  for (const [weightG, toJewelry, toBar] of rows) {
    await prisma.barConversionFee.create({
      data: {
        weightG: D(weightG),
        barToJewelry: D(toJewelry),
        barToBar: D(toBar),
        createdById: adminId,
      },
    });
  }
  console.log(`  ຄ່າປ່ຽນ (bar)....... ${rows.length}`);
}

/** TOR §3.5 — ຄ່າອ່ອນ ປັດຈຸບັນ = 400,000 LAK. */
async function seedSoftGoldFee(adminId: string) {
  const existing = await prisma.softGoldFeeSnapshot.count();
  if (existing > 0) {
    console.log('  ຄ່າອ່ອນ............. already seeded (append-only)');
    return;
  }
  await prisma.softGoldFeeSnapshot.create({
    data: { value: D(400_000), createdById: adminId },
  });
  console.log('  ຄ່າອ່ອນ............. 400,000 LAK');
}

/** TOR §3.6 — ປະເພດຄຳ ແລະ ລາຍການຄຳ. */
async function seedGoldTypesAndItems() {
  const goldTypes = [
    { code: 'GOOD', nameLo: 'ຄຳດີ', isStockType: true, sortOrder: 1 },
    { code: 'HUMP', nameLo: 'ຄຳຫຍຸບ', isStockType: true, sortOrder: 2 },
    { code: 'BAR', nameLo: 'ຄຳແທ່ງ', isStockType: true, sortOrder: 3 },
    { code: 'BOILED', nameLo: 'ຄຳຕົ້ມ', isStockType: true, sortOrder: 4 },
    { code: 'TO_CASH', nameLo: 'ປ່ຽນເປັນເງິນ', isStockType: false, sortOrder: 5 },
    { code: 'FREE_SWAP', nameLo: 'ປ່ຽນຟຣີ', isStockType: false, sortOrder: 6 },
  ];
  for (const t of goldTypes) {
    await prisma.goldType.upsert({ where: { code: t.code }, update: t, create: t });
  }

  const goldItems = [
    { code: 'BRACELET', nameLo: 'ສາຍແຂນ', sortOrder: 1 },
    { code: 'NECKLACE', nameLo: 'ສາຍຄໍ', sortOrder: 2 },
    { code: 'BANGLE', nameLo: 'ກີ້', sortOrder: 3 },
    { code: 'RING', nameLo: 'ແຫວນ', sortOrder: 4 },
    { code: 'EARRING', nameLo: 'ຕ່າງຫູ', sortOrder: 5 },
    { code: 'BELT', nameLo: 'ສາຍແອວ', sortOrder: 6 },
    { code: 'GOLD_BAR', nameLo: 'ຄຳແທ່ງ', sortOrder: 7 },
  ];
  for (const i of goldItems) {
    await prisma.goldItem.upsert({ where: { code: i.code }, update: i, create: i });
  }
  console.log(`  ປະເພດຄຳ / ລາຍການຄຳ. ${goldTypes.length} / ${goldItems.length}`);
}

/**
 * ແຫຼ່ງຮັບເຂົ້າ / ແຫຼ່ງສົ່ງອອກ (TOR §7.1, §7.2, §8).
 * `tracksGoldApAr` marks the partners whose movements post to AP/AR (GOLD).
 */
async function seedPartnerSources() {
  const partners = [
    { code: 'EASY', nameLo: 'EASY', direction: 'IN' as const, tracksGoldApAr: true, sortOrder: 1 },
    { code: 'FACTORY', nameLo: 'FACTORY', direction: 'BOTH' as const, tracksGoldApAr: true, sortOrder: 2 },
    { code: 'OUTSOURCE_SMITH', nameLo: 'ຊ່າງນອກ', direction: 'BOTH' as const, tracksGoldApAr: true, sortOrder: 3 },
    { code: 'OTHER', nameLo: 'ອື່ນໆ', direction: 'BOTH' as const, tracksGoldApAr: true, sortOrder: 4 },
    { code: 'CABINET', nameLo: 'ຕູ້ເຄື່ອງ', direction: 'OUT' as const, tracksGoldApAr: false, sortOrder: 5 },
    { code: 'WHOLESALES', nameLo: 'WHOLESALES', direction: 'OUT' as const, tracksGoldApAr: false, sortOrder: 6 },
    { code: 'WITHDRAW', nameLo: 'WITHDRAW', direction: 'OUT' as const, tracksGoldApAr: true, sortOrder: 7 },
    { code: 'CASHIER', nameLo: 'Cashier', direction: 'IN' as const, tracksGoldApAr: false, sortOrder: 8 },
  ];
  for (const p of partners) {
    await prisma.partnerSource.upsert({ where: { code: p.code }, update: p, create: p });
  }
  console.log(`  partner sources..... ${partners.length}`);
}

async function seedBankAccounts() {
  const banks = [
    { code: 'BCEL', nameLo: 'BCEL', sortOrder: 1 },
    { code: 'LDB', nameLo: 'LDB', sortOrder: 2 },
    { code: 'OTHER_BANK', nameLo: 'Other Bank', sortOrder: 3 },
  ];
  for (const b of banks) {
    await prisma.bankAccount.upsert({ where: { code: b.code }, update: b, create: b });
  }
  console.log(`  bank accounts....... ${banks.length}`);
}

async function seedCabinets() {
  const cabinets = [
    { code: 'CAB-01', nameLo: 'ຕູ້ເຄື່ອງ 01' },
    { code: 'CAB-02', nameLo: 'ຕູ້ເຄື່ອງ 02' },
  ];
  for (const c of cabinets) {
    await prisma.cabinet.upsert({ where: { code: c.code }, update: c, create: c });
  }
  console.log(`  cabinets............ ${cabinets.length}`);
}

/**
 * TOR §8.4 / §7.4 — default AP/AR (GOLD) posting rules.
 *
 * The TOR contradicts itself here: §8.1 describes gold sent out to
 * FACTORY / ຊ່າງນອກ as AR, while §8.4's rule list and §7.4's FACTORY
 * completion step both post it to AP. The shop settled this with the customer
 * and chose §8.4 + §7.4 — every movement lands on AP:
 *
 *   Stock IN  (EASY / FACTORY / ຊ່າງນອກ / ອື່ນໆ) -> +AP  (KPV owes gold)
 *   Stock OUT (FACTORY / ຊ່າງນອກ / ອື່ນໆ / WITHDRAW) -> -AP  (obligation cleared)
 *
 * §8.4's six bullets are three pairs, one per relationship — the shop
 * confirmed this reading:
 *
 *   1 ↔ 2   IN from ຊ່າງນອກ/ອື່ນໆ   ↔  OUT to ຊ່າງນອກ/ອື່ນໆ
 *   3 ↔ 4   IN from EASY             ↔  OUT to WITHDRAW
 *   5 ↔ 6   IN from FACTORY          ↔  OUT to FACTORY
 *
 * Pair 3↔4 is the one that needs care: the two halves name different
 * partners, yet they are the same obligation, so the WITHDRAW rule carries
 * `counterparty: 'EASY'` and both halves settle on EASY's row. Without it
 * EASY would climb forever while WITHDRAW ran negative.
 *
 * Consequence to know about: with every movement on AP, the AR (GOLD) module
 * has no posting rule and stays at zero — which matches §8.3, whose table is
 * itself labelled with AP columns.
 *
 * This table is Admin-editable, so reversing the decision is a data edit, not
 * a code change.
 */
async function seedGoldApArPostingRules() {
  const existing = await prisma.goldApArPostingRule.count();
  if (existing > 0) {
    console.log('  AP/AR gold rules.... already seeded');
    return;
  }
  const partners = await prisma.partnerSource.findMany({ where: { tracksGoldApAr: true } });
  const byCode = new Map(partners.map((p) => [p.code, p.id]));

  const rules: Array<{
    scope: 'NEW' | 'OLD';
    type: 'IN' | 'OUT';
    code: string;
    side: 'AP' | 'AR';
    sign: number;
    /** Book against this partner instead of `code` (see §8.4 pair 3↔4). */
    counterparty?: string;
    note: string;
  }> = [
    // Gold received into the shop -> +AP (KPV ຕິດໜີ້ຄຳຄູ່ຄ້າ).
    { scope: 'NEW', type: 'IN', code: 'EASY', side: 'AP', sign: 1, note: 'Stock IN ຈາກ EASY -> +AP (ຕິດໜີ້ຄຳ EASY)' },
    { scope: 'NEW', type: 'IN', code: 'FACTORY', side: 'AP', sign: 1, note: 'Stock IN ຈາກ FACTORY -> +AP (ຕິດໜີ້ຄຳ FACTORY)' },
    { scope: 'NEW', type: 'IN', code: 'OUTSOURCE_SMITH', side: 'AP', sign: 1, note: 'Stock IN ຈາກ ຊ່າງນອກ -> +AP (ຕິດໜີ້ຄຳ ຊ່າງນອກ)' },
    { scope: 'NEW', type: 'IN', code: 'OTHER', side: 'AP', sign: 1, note: 'Stock IN ຈາກ ອື່ນໆ -> +AP (ຕິດໜີ້ຄຳ ອື່ນໆ)' },
    // Gold sent out -> -AP (ລົບລ້າງພັນທະສົ່ງມອບຄຳ).
    { scope: 'OLD', type: 'OUT', code: 'FACTORY', side: 'AP', sign: -1, note: 'Stock OUT ໄປ FACTORY -> -AP (ລົບລ້າງພັນທະສົ່ງມອບຄຳ FACTORY)' },
    { scope: 'OLD', type: 'OUT', code: 'OUTSOURCE_SMITH', side: 'AP', sign: -1, note: 'Stock OUT ໄປ ຊ່າງນອກ -> -AP (ລົບລ້າງພັນທະສົ່ງມອບຄຳ ຊ່າງນອກ)' },
    { scope: 'OLD', type: 'OUT', code: 'OTHER', side: 'AP', sign: -1, note: 'Stock OUT ໄປ ອື່ນໆ -> -AP (ລົບລ້າງພັນທະສົ່ງມອບຄຳ ອື່ນໆ)' },
    // Handing gold back to EASY settles the payable.
    {
      scope: 'NEW',
      type: 'OUT',
      code: 'WITHDRAW',
      side: 'AP',
      sign: -1,
      // §8.4 pairs this with the EASY intake above, so it clears EASY's row.
      counterparty: 'EASY',
      note: 'Stock OUT WITHDRAW -> -AP (ລົບລ້າງພັນທະ EASY)',
    },
  ];

  let created = 0;
  for (const r of rules) {
    const partnerId = byCode.get(r.code);
    if (!partnerId) continue;
    await prisma.goldApArPostingRule.create({
      data: {
        scope: r.scope,
        type: r.type,
        partnerId,
        counterpartyId: r.counterparty ? (byCode.get(r.counterparty) ?? null) : null,
        side: r.side,
        sign: r.sign,
        note: r.note,
      },
    });
    created += 1;
  }
  console.log(`  AP/AR gold rules.... ${created}`);
}

/** TOR §3.7 — ໝວດລາຍຮັບ / ລາຍຈ່າຍ ຕັ້ງຕົ້ນ. */
async function seedIncomeExpenseCategories() {
  const rows = [
    { code: 'SALARY', nameLo: 'ເງິນເດືອນ', kind: 'EXPENSE' as const, sortOrder: 1 },
    { code: 'RENT', nameLo: 'ຄ່າເຊົ່າ', kind: 'EXPENSE' as const, sortOrder: 2 },
    { code: 'UTILITY', nameLo: 'ຄ່ານ້ຳ-ໄຟ', kind: 'EXPENSE' as const, sortOrder: 3 },
    { code: 'TRANSPORT', nameLo: 'ຄ່າຂົນສົ່ງ', kind: 'EXPENSE' as const, sortOrder: 4 },
    { code: 'OTHER_EXPENSE', nameLo: 'ລາຍຈ່າຍອື່ນໆ', kind: 'EXPENSE' as const, sortOrder: 5 },
    { code: 'INTEREST', nameLo: 'ດອກເບ້ຍ', kind: 'INCOME' as const, sortOrder: 6 },
    { code: 'OTHER_INCOME', nameLo: 'ລາຍຮັບອື່ນໆ', kind: 'INCOME' as const, sortOrder: 7 },
  ];
  for (const row of rows) {
    await prisma.incomeExpenseCategory.upsert({
      where: { code: row.code },
      update: row,
      create: row,
    });
  }
  console.log(`  ລາຍການຮັບຈ່າຍ...... ${rows.length}`);
}

/** TOR §9.1 — ປະເພດລາຍການ AP-AR (Cash) ຕັ້ງຕົ້ນ. */
async function seedApArCashCategories() {
  const rows = [
    { code: 'LABOR_FEE', nameLo: 'ຄ່າແຮງຊ່າງ', side: 'AP' as const, sortOrder: 1 },
    { code: 'GOLD_PURCHASE', nameLo: 'ຄ່າຊື້ຄຳ', side: 'AP' as const, sortOrder: 2 },
    { code: 'CREDIT', nameLo: 'ສິນເຊື່ອລູກຄ້າ', side: 'AR' as const, sortOrder: 3 },
    { code: 'GOLD_SALE', nameLo: 'ຄ່າຂາຍຄຳຄ້າງຮັບ', side: 'AR' as const, sortOrder: 4 },
    { code: 'OTHER', nameLo: 'ອື່ນໆ', side: null, sortOrder: 5 },
  ];
  for (const row of rows) {
    await prisma.apArCashCategory.upsert({
      where: { code: row.code },
      update: row,
      create: row,
    });
  }
  console.log(`  ປະເພດ AP-AR (Cash). ${rows.length}`);
}

async function main() {
  console.log('\nSeeding KPV gold store database...\n');
  const adminId = await seedUsers();
  await seedWeightTiers();
  await seedBuybackDeductions(adminId);
  await seedPriceSnapshot(adminId);
  await seedExchangeRate(adminId);
  await seedJewelryConversionFees(adminId);
  await seedBarConversionFees(adminId);
  await seedSoftGoldFee(adminId);
  await seedGoldTypesAndItems();
  await seedPartnerSources();
  await seedBankAccounts();
  await seedCabinets();
  await seedGoldApArPostingRules();
  await seedIncomeExpenseCategories();
  await seedApArCashCategories();
  console.log('\nSeed complete.\n');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
